<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ3JaPF5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ3JaPF5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ3JaPF5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ3JaPF5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZ3JaPF5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Z3JaPF5',
    'container.build_id' => 'b45c52d6',
    'container.build_time' => 1653956959,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ3JaPF5');
